<form action="/login/login" method="post">
    <!-- Email input -->
    <div class="form-outline mb-4">
        <input type="email" name='email' id="form2Example1" class="form-control"
        value="<?php echo $_POST['email']?>" />
        <label class="form-label" for="form2Example1">Email address</label>
    </div>

    <!-- Password input -->
    <div class="form-outline mb-4">
        <input type="password" name="password" id="form2Example2" class="form-control"
        value="<?php echo $_POST['password']?>"/>
        <label class="form-label" for="form2Example2">Password</label>
    </div>

    <!-- 2 column grid layout for inline styling -->
    <div class="row mb-4">

        <!-- Submit button -->
        <button type="submit" class="btn btn-primary btn-block mb-4">Log in</button>

        <!-- Register buttons -->
        <div class="text-center">
            <p>Not a member? <a href="/signup/">Register</a></p>
        </div>
    </div>
</form>
